import { Providers } from "./provider";
import Home from "./home";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Home>{children}</Home>
        </Providers>
      </body>
    </html>
  );
}
